"""FX rate fetching, snapshot storage, baseline computation, and monitoring cycle."""

import logging
from datetime import datetime, timezone

import httpx

from app.config import settings
from app.db import crud

logger = logging.getLogger(__name__)


# ──── Global baselines ────
# Hardcoded benchmark mid-market rates for common corridors.
# These serve as a fallback when a user has no personal history.

GLOBAL_BASELINES: dict[str, float] = {
    "USD_INR": 82.5,
    "USD_PHP": 55.5,
    "USD_MXN": 17.2,
    "USD_NGN": 770.0,
    "USD_PKR": 280.0,
    "USD_BDT": 110.0,
    "USD_VND": 24_300.0,
    "USD_KES": 153.0,
    "GBP_INR": 104.0,
    "GBP_PKR": 355.0,
    "GBP_NGN": 980.0,
    "EUR_INR": 90.0,
    "EUR_PHP": 60.5,
    "EUR_NGN": 840.0,
    "CAD_INR": 61.5,
    "AUD_INR": 54.0,
}


def get_global_baseline(corridor: str) -> float | None:
    """Return the hardcoded benchmark rate for *corridor*, or None if unknown."""
    return GLOBAL_BASELINES.get(corridor)


# ──── Task 2.1 — FX API client ────


async def fetch_fx_rate(base_currency: str, target_currency: str) -> dict | None:
    """Fetch a live FX rate from ExchangeRate-API (v6 pair endpoint).

    Returns a dict with keys ``rate``, ``base``, ``target``, ``timestamp``
    on success, or ``None`` on any error (timeout, HTTP failure, bad payload).
    """
    url = f"{settings.fx_api_base_url}/{settings.fx_api_key}/pair/{base_currency}/{target_currency}"
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            data = resp.json()

        if data.get("result") != "success":
            logger.warning(
                "ExchangeRate-API returned non-success result for %s/%s: %s",
                base_currency,
                target_currency,
                data.get("error-type", "unknown"),
            )
            return None

        return {
            "rate": float(data["conversion_rate"]),
            "base": base_currency,
            "target": target_currency,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    except httpx.HTTPStatusError as exc:
        logger.error(
            "ExchangeRate-API HTTP error %s for %s/%s: %s",
            exc.response.status_code,
            base_currency,
            target_currency,
            exc.response.text,
        )
    except httpx.RequestError as exc:
        logger.error(
            "ExchangeRate-API request failed for %s/%s: %s",
            base_currency,
            target_currency,
            exc,
        )
    except (KeyError, ValueError, TypeError) as exc:
        logger.error(
            "ExchangeRate-API unexpected payload for %s/%s: %s",
            base_currency,
            target_currency,
            exc,
        )
    return None


# ──── Task 2.3 — Rate snapshot storage ────


async def store_snapshot(
    corridor: str,
    rate: float,
    fees: float,
    amount_sent: float,
    provider: str = "exchangerate-api",
) -> str:
    """Compute the recipient amount and persist a rate snapshot.

    Returns the ``snapshot_id`` generated by the data layer.
    """
    recipient_amount = (amount_sent - fees) * rate

    snapshot_data: dict = {
        "corridor": corridor,
        "rate": str(rate),
        "fees": str(fees),
        "amount_sent": str(amount_sent),
        "recipient_amount": str(recipient_amount),
        "provider": provider,
    }

    snapshot_id = await crud.store_rate_snapshot(snapshot_data)
    logger.info(
        "Stored rate snapshot %s for %s (rate=%.4f, recipient_amount=%.2f)",
        snapshot_id,
        corridor,
        rate,
        recipient_amount,
    )
    return snapshot_id


# ──── Task 2.4 — Personal baseline calculator ────


async def compute_personal_baseline(corridor: str) -> dict | None:
    """Compute a personal baseline from the last 14 days of snapshots.

    Returns a dict with ``avg_recipient_amount``, ``avg_rate``, and
    ``snapshot_count``, or ``None`` if there are no snapshots.
    """
    snapshots = await crud.get_rate_snapshots(corridor, days=14)
    if not snapshots:
        return None

    total_recipient_amount = 0.0
    total_rate = 0.0
    count = 0

    for snap in snapshots:
        try:
            total_recipient_amount += float(snap["recipient_amount"])
            total_rate += float(snap["rate"])
            count += 1
        except (KeyError, ValueError, TypeError) as exc:
            logger.warning("Skipping malformed snapshot %s: %s", snap.get("snapshot_id"), exc)

    if count == 0:
        return None

    return {
        "avg_recipient_amount": total_recipient_amount / count,
        "avg_rate": total_rate / count,
        "snapshot_count": count,
    }


# ──── Task 2.6 — Scheduler entry point ────


async def run_monitoring_cycle() -> dict:
    """Run one full monitoring cycle across all active corridors.

    For each corridor the function:
      1. Fetches the latest FX rate.
      2. Stores a rate snapshot.
      3. (Future) Checks thresholds via the decision engine.

    Returns a summary dict with ``corridors_checked``, ``snapshots_stored``,
    and ``alerts_triggered``.
    """
    corridors = await crud.get_all_active_corridors()
    logger.info("Monitoring cycle started — %d active corridor(s)", len(corridors))

    corridors_checked = 0
    snapshots_stored = 0
    alerts_triggered = 0

    for corridor_info in corridors:
        corridor: str = corridor_info["corridor"]
        average_amount: float = float(corridor_info.get("average_amount", 500))

        # Derive base / target from corridor string (e.g. "USD_INR")
        parts = corridor.split("_")
        if len(parts) != 2:
            logger.warning("Skipping corridor with unexpected format: %s", corridor)
            continue

        base_currency, target_currency = parts
        corridors_checked += 1

        # 1. Fetch live rate
        rate_data = await fetch_fx_rate(base_currency, target_currency)
        if rate_data is None:
            logger.warning("Could not fetch rate for %s — skipping", corridor)
            continue

        # 2. Store snapshot (fees default to 0 for mid-market rate captures)
        await store_snapshot(
            corridor=corridor,
            rate=rate_data["rate"],
            fees=0.0,
            amount_sent=average_amount,
        )
        snapshots_stored += 1

        # 3. Threshold check — decision_engine integration (placeholder)
        # TODO: import and call decision_engine.check_thresholds when available
        # alerts_triggered += ...

    summary = {
        "corridors_checked": corridors_checked,
        "snapshots_stored": snapshots_stored,
        "alerts_triggered": alerts_triggered,
    }
    logger.info("Monitoring cycle complete: %s", summary)
    return summary
