"""Narrative and memo endpoints: AI-generated persona narratives and risk memo download."""
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from backend.models.database import get_db
from backend.models.models import Region
from backend.services.climate_data import get_climate_data
from backend.services.climate_engine import compute_yield_stress
from backend.services.financial_translator import translate_financial
from backend.services.ai.bedrock_client import BedrockClient
from backend.services.ai.narrative_service import NarrativeService

router = APIRouter()

# Shared service instances
_bedrock_client = BedrockClient()
_narrative_service = NarrativeService(_bedrock_client)


def _get_region_or_404(region_id: str, db: Session) -> Region:
    region = db.query(Region).filter_by(region_id=region_id).first()
    if not region:
        raise HTTPException(status_code=404, detail="Region not found")
    return region


async def _build_context(region: Region) -> dict:
    """Build the context data dict needed by NarrativeService."""
    climate = await get_climate_data(region.region_id, region.lat, region.lng)
    stress = compute_yield_stress(
        climate["temperature_anomaly"],
        climate["drought_index"],
        climate["rainfall_anomaly"],
        climate["ndvi_score"],
        climate["soil_moisture"],
    )
    financial = translate_financial(
        region.base_loan_rate, region.base_pd, region.base_premium, stress,
    )
    return {
        "region_name": region.name,
        "primary_crop": region.primary_crop,
        "climate_inputs": climate,
        "yield_stress_score": stress,
        "financial_outputs": financial,
    }


@router.get("/region/{region_id}/narrative")
async def get_narrative(
    region_id: str,
    panel: str = Query(default="loan_officer"),
    db: Session = Depends(get_db),
):
    """Get AI-generated narrative for a specific persona panel."""
    valid_panels = ["loan_officer", "farmer", "scientist"]
    if panel not in valid_panels:
        raise HTTPException(status_code=400, detail=f"Invalid panel. Must be one of: {valid_panels}")

    region = _get_region_or_404(region_id, db)
    context = await _build_context(region)
    narrative = await _narrative_service.generate(context, panel)
    return {"panel": panel, "narrative": narrative}


@router.get("/region/{region_id}/memo")
async def get_memo(region_id: str, db: Session = Depends(get_db)):
    """Download a plain-text risk memo for a region."""
    region = _get_region_or_404(region_id, db)
    context = await _build_context(region)

    stress = context["yield_stress_score"]
    fin = context["financial_outputs"]
    climate = context["climate_inputs"]

    memo = f"""TERRALEND RISK MEMO
{'=' * 50}
Region: {region.name}
Primary Crop: {region.primary_crop}
Date: Generated on demand

CLIMATE ASSESSMENT
{'-' * 50}
Temperature Anomaly: {climate['temperature_anomaly']}°C
Drought Index: {climate['drought_index']}/100
Rainfall Anomaly: {climate['rainfall_anomaly']}%
NDVI Health: {climate['ndvi_score']}/100
Soil Moisture: {climate['soil_moisture']}/100

YIELD STRESS SCORE: {stress}/100

FINANCIAL TERMS
{'-' * 50}
Interest Rate: {fin['interest_rate']}%
Rate Floor: {fin['rate_floor']}%
Rate Ceiling: {fin['rate_ceiling']}%
Probability of Default: {fin['probability_of_default'] * 100:.1f}%
Insurance Premium: ${fin['insurance_premium']:,.2f}
Repayment Term: {fin['repayment_months']} months
Repayment Flexibility: {fin['repayment_flexibility']}/100

RISK SUMMARY
{'-' * 50}
{'HIGH RISK' if stress > 70 else 'MODERATE RISK' if stress > 40 else 'LOW RISK'}: """

    if stress > 70:
        memo += (
            f"Yield stress of {stress}/100 indicates significant climate exposure. "
            f"Elevated PD of {fin['probability_of_default']*100:.1f}% warrants close monitoring. "
            f"Consider requiring crop insurance and shorter review cycles."
        )
    elif stress > 40:
        memo += (
            f"Yield stress of {stress}/100 indicates moderate climate exposure. "
            f"Standard underwriting terms apply with periodic review recommended."
        )
    else:
        memo += (
            f"Yield stress of {stress}/100 indicates favorable conditions. "
            f"Standard terms with potential for rate improvement on next review."
        )

    memo += f"""

{'=' * 50}
Generated by TerraLend Climate Risk Engine v1.0
"""

    return PlainTextResponse(
        content=memo,
        headers={"Content-Disposition": f"attachment; filename=risk_memo_{region_id}.txt"},
    )
